CREATE DATABASE CALC_BILL CHARACTER SET utf8mb4 COLLATE utf8mb4_polish_ci;

CREATE TABLE OWNER (
    ID        INT(11)       NOT NULL AUTO_INCREMENT,
    NAME      TEXT          NOT NULL,
    SURNAME   TEXT          NOT NULL,
    PRIMARY KEY (ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE PAYMENTS (
    ID        INT(11)       NOT NULL AUTO_INCREMENT,
    PAY_OWNER INT(11)       NOT NULL,
    KIND      TINYTEXT      NOT NULL,
    AMOUNT    DOUBLE        NOT NULL,
    DATE      TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PAY_OWNER) REFERENCES OWNER (ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;